### ISSUE TITLE
Error with click on tabs

### ISSUE THREAD

**Issue by ricardorlg** [agoda-com/Kakao#105]
More Than a bug is a question, Im creating a Kview in a tab with this code, 
` KView {
            withParent { withClassName(endsWith("TabView")) }
            withText(sectionName)
        }` after that I perform a scrollTo and a click, this actions happens but then I get an error `Error performing 'single click - At Coordinates: 922, 272 and precision: 16, 16' on view '(has parent matching: (with class name: a string ending with "TabView") and with text: is "Test Tab")'` , any idea in what is the problem.

**Comment by Unlimity** [comment]
Hey there!
Can you please provide the full stacktrace of your issue? Since this message does not tell the real reason of execution failure.

**Comment by Unlimity** [comment]
Closing this issue due to no response.
