### ISSUE TITLE
Support for AndroidX Espresso

### ISSUE THREAD

**Issue by audkar** [agoda-com/Kakao#109]
#### Steps to reproduce:

  1. Replace support lib Espresso dependency with AndroidX one
```
'com.android.support.test.espresso:espresso-core:3.0.2'
to
'androidx.test.espresso:espresso-core:3.1.0-alpha4'
```
  2. Write test which with `click()` assertion. e.g. `screen.button.click()`
  
#### Observed Results:

 Compiler error: 
`Cannot access class 'android.support.test.espresso.action.GeneralLocation'. Check your module classpath for missing or conflicting dependencies`
  
#### Expected Results:

 Test code should compile

AndroidX library will be co-existing with supportLib for some time. Maybe would be possible to have separate artifact for AndroidX?

**Comment by VerachadW** [comment]
Hi, @audkar. We will migrate to AndroidX when it moves out from the alpha release. We don't have the plan to create a new artifact right now.

**Comment by ateek** [comment]
@cdsap  thanks for the effort. any news about publishing the artifact.

**Comment by Vacxe** [comment]
@ateek I suppose that I could finish it in couple days. And sorry for delay.
