### ISSUE TITLE
KRecyclerView multiple childs assert not success

### ISSUE THREAD

**Issue by alorma** [agoda-com/Kakao#110]
#### Steps to reproduce:

  1. Build `Screen` with recycler view
  2. On your code, set more than one item at recyclerview adapter
  3. Try to do assert with more than one children
  
#### Observed Results:

https://gist.github.com/alorma/4b2cf664f6f92c6ba4f9abc8416c335e

```
+---------->AppCompatTextView{id=2131361887, res-name=addressView, visibility=VISIBLE, width=954, height=126, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=true, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.support.constraint.ConstraintLayout$LayoutParams@fff2b2b, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, text=Calle Llull nº 113 - 119, 08025 Barcelona, input-type=0, ime-target=false, has-links=false} ****MATCHES****
```

As you can see, the item shows a   `****MATCHES****`

#### Expected Results:

Two assertions success, as you can see, the second assert ("Calle Llull nº 113 - 119, 08025 Barcelona") is on the output of the view hierarchy
  
#### Relevant Code:

  ```
        screen {
            address {
                firstChild<AddressItem> {
                    name { hasText("Calle falsa nº 123, 08112 Springfield") }
                }
                lastChild<AddressItem> {
                    name { hasText("Calle Llull nº 113 - 119, 08025 Barcelona") }
                }
            }
        }
  ```

**Comment by Unlimity** [comment]
That is truly unexpected behavior. Can you share with us the version of Kakao you're using?

**Comment by alorma** [comment]
kakaoVersion = "1.4.0"

**Comment by Unlimity** [comment]
Thanks! I will investigate issue in when I will have free time. But for starters it seems that `lastChild` extension function's matcher is not matching correctly. You can try replacing this call with `childAt<AddressItem>(size() - 1) {` to see if there is any difference.
Cheers!

**Comment by Unlimity** [comment]
Hi there! I'm very sorry that I didn't have any time lately to look into your issue. Have you managed to resolve it yourself by any chance?

**Comment by dsceinos** [comment]
Hi, I'm getting the same @alorma 's error.

**Output:**
https://gist.github.com/dsceinos/43df91092dc9cd5e217cd1e156ae2a26

**Code:**
` screen {
            bundlesRecycler {
                hasSize(2)
                childAt<Screen.Item>(0) {
                  titleTextView { containsText(item1.description) }
                }
                childAt<Screen.Item>(1) {
                   titleTextView { containsText(item2.description) }
                }
            }
        }`

**Comment by Unlimity** [comment]
Can you please provide your screen class source?

**Comment by Unlimity** [comment]
I saw your exception, and the matcher does not matching recycler view as your item's parent. My guess here is that you haven't declared your item class correctly.

**Comment by dsceinos** [comment]
I've recheck item declaration and I found that I forgot to add item's view constructor with `parent` parameter.
Thanks!

**Comment by Unlimity** [comment]
Nice. I suppose @alorma had same problem, so I'm closing this issue.
