### ISSUE TITLE
Add KSpinner view component and related functions

### ISSUE THREAD

**Issue by pokk** [agoda-com/Kakao#118]
Kakao is an awesome library for reducing our test code. I'm using Kakao for testing my project but there's no spinner component to test spinner.
Instead of using Kakao KView, I just can use original `onView` or `onData` to implement test code.

I have a few functions as the following below

```kotlin
fun selectItem(position: Int)
fun selectItem(content: String)
fun withText(content: String)
fun withText(stringId: Int)
```

If there is any function should be added, please let me know.

**Comment by Unlimity** [comment]
Hey there!
Thanks for reaching out! I will look if there's anything we can do when I have free time. As I recall, spinner uses another window to show the selection options, so I'm not sure that we can easily implement it as part of Kakao. But I will try. Cheers!

**Comment by pokk** [comment]
Thank you for your replying.

Just make sure this function is necessary or whether someone is working on it. If no one is working on it currently, I can implement it! 👍
I'll send PR after I finish.

**Comment by michaelbukachi** [comment]
I'd like to pick up on this issue.
