### ISSUE TITLE
Add Matcher withTag(tagValue)

### ISSUE THREAD

**Issue by whalemare** [agoda-com/Kakao#121]
Hello, thanks for your library.
Can you add function for find views by it tag, for better testing-developer experince :)) 

For now, if you want find view by tag you need write code like this:
```kotlin
val tagValue: Any = "tag"
val view = KView { withMatcher(ViewMatchers.withTagValue(Matchers.`is`(tagValue))) }  
```

It would be great to reduce this code to:
```kotlin
val tagValue: Any = "tag"
val view = KView { withTag(tagValue) }  
```

Thanks!

**Comment by Unlimity** [comment]
Matcher is added and already merged to master!
Happy testing!
