### ISSUE TITLE
AndroidX migration

### ISSUE THREAD

**Issue by Unlimity** [agoda-com/Kakao#130]
Prior to releasing 2.0 we need to decide how we want to go with the androidx artifacts. The popular opinion I heard is to make a branch at current state and release it as `2.0.0-support`, migrate master branch to androidx and release it as `2.0.0`.

What are your thoughts on this?

**Comment by cdsap** [comment]
I'm agree with the approach of `2.0.0-support` and `2.0.0`

**Comment by Unlimity** [comment]
Done 👍
