### ISSUE TITLE
Get view matcher from screen context

### ISSUE THREAD

**Issue by romanpozd-tg17** [agoda-com/Kakao#134]
Hey, 
I trying to refactor tests written with Espresso to Kakao
Can't figure out how to refactor this line. 
   `onView(titleTextMatcher).check(isCompletelyAbove(googleBtnMatcher))` 

Tried something like that.. but isCompletelyAbove() expect to receive googleButton matcher that I can't retrieve. 

        signinScreen {
            googleButton {}
            title {
                isCompletelyDisplayed()
                matches { isCompletelyAbove(this@signinScreen.googleButton) }
            }
        }

Thanks.

**Comment by cdsap** [comment]
Hi @romanpozd-tg17  Thanks for using Kakao. 
`isCompletelyAbove` is a ViewAssertion not included in the Kakao lib. 

Kakao offers the possibility to define custom assertions through:
```
   fun assert(function: () -> ViewAssertion) {
        view.check(function.invoke())
    }
```

so you can implement it like 
```
   title {
       assert {
           isCompletelyAbove(ViewMatchers.withId(R.id.signinbutton))
       }
   }
```

@Unlimity let me know if you want I open a PR including this new PositionAssertion `isCompletelyAbove`

**Comment by romanpozd-tg17** [comment]
@cdsap @Unlimity Thank you guys!

**Comment by Unlimity** [comment]
@romanpozd-tg17 the feature has been added and will be available in the next release. Closing this issue. Thank you for reaching out!
