### ISSUE TITLE
Can't be called in this context by implicit receiver

### ISSUE THREAD

**Issue by Dimezis** [agoda-com/Kakao#135]
On a new 2.0.0 AndroidX version of the lib, the following code gives a compilation error:
`val lol Can't be called in this context by implicit receiver. Use explicit one if necessary`

```Kotlin
val lol = "text"
val view = KTextView { containsText(lol) }
```

It is fixable by adding `this@ClassName.lol` to a `lol` val. 
But I'm kinda missing what has changed since 2.0.0 that I can't use an implicit receiver anymore.
I have dozens of similar cases using the `ViewBuilder`, and after migration to AndroidX and 2.0.0 all of them require adding an explicit receiver.

Can you please clarify what's happening here and potentially fix it?

**Comment by Dimezis** [comment]
Got it. Thank you for clarification.

**Comment by Unlimity** [comment]
Closing this issue as the questions has been answered.
