### ISSUE TITLE
DrawableMatcher should correctly match provided Drawable objects

### ISSUE THREAD

**Issue by ahampe** [agoda-com/Kakao#137]
#### Steps to reproduce:

  1. Attempt to match a drawable in a screen with `hasDrawable(@DrawableRes resId: Int)` and observe test success.
  2. Attempt to match same drawable with `hasDrawable(drawable: Drawable)`, passing in a loaded drawable from the previous resource ID. The test will fail.
  
#### Observed Results:

Failure with exception `android.content.res.Resources$NotFoundException: Resource ID #0xffffffff`

It seems like `DrawableMatcher.matchesSafely` mixes up the assignment of the drawable parameter. It should probably be assigned to the `expectedDrawable`, not the `convertDrawable`.

**Comment by ahampe** [comment]
I forked the project and have a branch with this fix, plus relevant tests. Should I put in a PR?

**Comment by cdsap** [comment]
@ahampe thanks for the interest. 
Sure, you can create a PR

**Comment by Unlimity** [comment]
Fix is merged. Closing this issue.
