### ISSUE TITLE
Kakao view for ScrollView

### ISSUE THREAD

**Issue by georgyR** [agoda-com/Kakao#139]
Now there is no KScrollView

**Comment by Unlimity** [comment]
Hi! First of all, thanks for reaching out.
But I don't recall that there were `KScrollView` in Kakao in the first place.
Can you tell me which version of Kakao had it?
Or I misunderstood your sentence and you want to request such feature?

**Comment by georgyR** [comment]
Hi. Yes, I want ScrollView supporting. Thank you for fast reaction and PR

**Comment by Unlimity** [comment]
Component is merged. Closing this issue.
