### ISSUE TITLE
hasDrawable doesn't work when ImageView has android:tint

### ISSUE THREAD

**Issue by tdekoning** [agoda-com/Kakao#179]
#### Steps to reproduce:

  1. Create a layout with an 
```
<ImageView android:src="R.drawable.my_icon" android:tint="R.color.white" android:layout_width="40dp" android:layout_height="40dp"/>
```
  2. Create a test that uses `hasDrawable(R.drawable.my_icon)`
  
#### Observed Results:

The method `hasDrawable` does not see the drawables as equal
  
#### Expected Results:

I expected the drawables to be equal, or provide a way to add the expected tint with the `hasDrawable` call

#### Possible workaround:
If i would comment out lines 86 until 88 (the canvas drawing) in [DrawableMatcher.kt](https://github.com/agoda-com/Kakao/blob/b8a6cf8f7679e32fffc7bf9aeea47f8e25a7d5ba/kakao/src/main/kotlin/com/agoda/kakao/common/matchers/DrawableMatcher.kt#L86) the comparing works, but i'm not sure if that will break anything.

**Comment by Unlimity** [comment]
Hi there! Thanks for reaching out.
Unfortunately, we do not support tinting matching at the moment. But you can submit a PR and extend the functionality of `DrawableMatcher` by checking if the target view has tint and applying it to the canvas that is being asserted.

**Comment by tdekoning** [comment]
Thanks for the tip, i'll see what i can do!

**Comment by Vacxe** [comment]
@tdekoning I think that this improvement can help you. Also, thank for let us know about this lack!

Cheers!

**Comment by tdekoning** [comment]
@Vacxe Thanks for the change and the quick response!

**Comment by tdekoning** [comment]
@Vacxe I've tried to test the code from your pull request, but it doesn't seem to work.
In my case i'm setting the `android:tint` and the (vector) drawable using `android:src`. The call `bitmap.sameAs(otherBitmap)` returns false and if i inspect the generated bitmaps, they aren't the same. It looks like an anti-alias or scaling issue.

I've tried to fix the issue myself, but i guess i do not understand imageview rendering well enough. Can you look into it?

**Comment by Vacxe** [comment]
@tdekoning sure, I'll try

**Comment by Vacxe** [comment]
@tdekoning BTW, does it work without tint? Just wanna find any clue.

**Comment by tdekoning** [comment]
@Vacxe is above enough information to trace the issue?

**Comment by Vacxe** [comment]
@tdekoning not yet. also with vector setup not sure that is possible. Let figure out how we can do it.

**Comment by Vacxe** [comment]
@tdekoning should be fixed. Could u test it or we can close ticket?

**Comment by tdekoning** [comment]
@Vacxe thanks!
We will test this next week, i will get back to you to report the results

**Comment by Vacxe** [comment]
@tdekoning can I close the ticket?

**Comment by tdekoning** [comment]
Sure, close it 👍
