### ISSUE TITLE
Add support for ViewPager2

### ISSUE THREAD

**Issue by anticafe** [agoda-com/Kakao#201]
It would be nice to have support for [ViewPager2](https://developer.android.com/jetpack/androidx/releases/viewpager2). I think because we've already have support for ViewPager, thus ViewPager2 would not take much time.

How do you think about it?

**Comment by Vacxe** [comment]
@anticafe I'll do it ASAP

**Comment by Vacxe** [comment]
@anticafe we will prepare release on this week
