### ISSUE TITLE
Tap spinner by text

### ISSUE THREAD

**Issue by hram** [agoda-com/Kakao#207]
Hi
Can you please help me. 
How can I do tap on spinner item with specific text. 
Spiner has emptyChildAt function. But in my case I need something like that emptyChildWithText()

**Comment by Unlimity** [comment]
Hey there! You can use Kakao's default list interaction API:
```kotlin
mySpinner {
  emptyChildWith {
    isInstanceOf(String::class.java)
    equals("MyText")
  } perform { click() }
}
```
Hope that helps.

**Comment by Unlimity** [comment]
Closing this issue due to no response
