### ISSUE TITLE
NestedScrollView not supported by ScrollTo ViewAction

### ISSUE THREAD

**Issue by albertlouisong** [agoda-com/Kakao#209]
#### Steps to reproduce:

  1. Create a layout with a nested scroll view
  2. Create a test that calls `scrollTo` on a view within that layout 
  
#### Observed Results:

  * Error is thrown that the scrollTo action failed
`androidx.test.espresso.PerformException: Error performing 'scroll to' on view '(with id: [view id])'.`

#### Expected Results:

  * UI test scrolls to the relevant view
  
#### Possible Workaround:

Currently using the solution from here, which just adds `NestedScrollView` as one of the assignable objects for `ScrollToAction`

https://stackoverflow.com/questions/35272953/espresso-scrolling-not-working-when-nestedscrollview-or-recyclerview-is-in-coor

**Comment by Unlimity** [comment]
Hi there! Thank you for raising this problem.
I'll see what I can do to improve.
