### ISSUE TITLE
Add TextInputLayoutAssertions.hasHint(@StringRes resId: Int)

### ISSUE THREAD

**Issue by igorwojda** [agoda-com/Kakao#217]
Now in `TextInputLayoutAssertions` we only have a way to verity hint by using string
`fun hasHint(hint: String)`

It would be nice to also have a way to use resource (to match `TextViewAssertions` class)
`hasHint(@StringRes resId: Int)`

**Comment by igorwojda** [comment]
For now I have solved this problem using extension function and helper function
```
fun KTextInputLayout.hasHint(@StringRes resId: Int) {
    getResourceString(resId)
}

private fun getResourceString(@StringRes resId: Int): String {
    val targetContext: Context = InstrumentationRegistry.getInstrumentation().targetContext
    return targetContext.resources.getString(resId)
}
```

**Comment by igorwojda** [comment]
Workaround
```
fun KTextInputLayout.hasHint(@StringRes resId: Int) {
    hasHint(getResourceString(resId))
}

private fun getResourceString(@StringRes resId: Int): String {
    val targetContext: Context = InstrumentationRegistry.getInstrumentation().targetContext
    return targetContext.resources.getString(resId)
}
```

**Comment by Unlimity** [comment]
Hey there! Thanks for reaching out!
That proposal sounds valid and useful, and I encourage you to submit a PR 👍

**Comment by igorwojda** [comment]
1. PR https://github.com/agoda-com/Kakao/pull/218

2. `CONTRIBUTING.md` file is a bit incomplete
points 1-3 are fine, but 
- pkt. 4 talks about running tests without any guides how to do so (command would be nice - just `./gradlew test` ?)
- pkt. 5 talks about running code coverage without any guides how to do so (AS build in? cmd?)
- pkt. 7 Running `git ls-files -z | while IFS= read -rd '' f; do tail -c1 < "$f" | read -r _ || echo >> "$f"; done` messes up with a lot of files untouched by PR

3. Also after running `TextInputLayoutTest` tests from IDE
![image](https://user-images.githubusercontent.com/530122/83144422-9aa19800-a0f3-11ea-85ba-5721d4d013b4.png)

I got this error 🤔
![image](https://user-images.githubusercontent.com/530122/83144400-8f4e6c80-a0f3-11ea-84b8-e71f12697179.png)

**Comment by Unlimity** [comment]
It seems that we need to revise contribution instructions 👍

**Comment by Vacxe** [comment]
Close: #219

**Comment by Unlimity** [comment]
PR with this feature has been merged
