### ISSUE TITLE
Misleading readme?

### ISSUE THREAD

**Issue by OliverCulleyDeLange** [agoda-com/Kakao#225]
#### Steps to reproduce:

  1. Read the [readme ](https://github.com/agoda-com/Kakao#create-kview)- See that ` val phone = KView { withId(R.id.phone) }` is declared as a KView
  2. Read further down in the [readme](https://github.com/agoda-com/Kakao#write-the-interaction) - See that `phone {
       hasText("971201771")
    }` uses the `hasText()` matcher

  3. Try it yourself, and wonder why hasText isn't available.
  4. Try changing KView to KTextView and everything works as expected. 
  
#### Observed Results:

KView does not have a `hasText()` matcher 
  
#### Expected Results:

KView should have a `hasText()` matcher
  

Am i missing something?

**Comment by Vacxe** [comment]
Please use `KTextView` instead of `KView`

**Comment by Unlimity** [comment]
Thank you for noticing and letting us know! The fix is merged now.
