### ISSUE TITLE
Migrate away from JCenter

### ISSUE THREAD

**Issue by steffandroid** [agoda-com/Kakao#248]
[JFrog](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/) has just announced that it will be shutting down JCenter on May 1st. JCenter is the sole repository hosting this library, so it will become unavailable after this date unless migrated to an alternative service.

**Comment by Vacxe** [comment]
@steffandroid Thanks for reporting. We have a plan migrate this library to must popular artifacts storage. No worries.

**Comment by steffandroid** [comment]
Excellent! Thanks for the update.

**Comment by gildor** [comment]
Any updates on this?

**Comment by Unlimity** [comment]
We're still in the process of getting access to company's account on maven central

**Comment by Vacxe** [comment]
@gildor hopefully we can smoothly migrate to Maven Central in next couple weeks and prepare a new release.

**Comment by antonbatishchev** [comment]
@steffandroid Hi! Following versions are now available in Central.
We are also working on CICD migration in order to release 2.4.1. to Central. thanks @Vacxe for help :) 

2.4.0
2.3.4
2.2.0
2.1.0
2.1.0-support
1.4.0-androidx

**Comment by Vacxe** [comment]
Repository has been migrated to https://github.com/KakaoAndroid/Kakao
