### ISSUE TITLE
Scroll to RecyclerView element that part can be off screen

### ISSUE THREAD

**Issue by szykam** [agoda-com/Kakao#253]
Imagine that you have a RecyclerView that accommodates item that can be large (in height) eg. 10 lines on TextView + Button, and also buttons can be distinguish by index so 1st one has text `Button 0`, 10th `Button 9`, and so on.
So if I want to click on the 10th button I'm able to scroll to 10th item in RecyclerView but button remains off screen and cannot be clicked. Library gives possibility to scroll to a view holder item but I'm able to figure out how to scroll a list so RecyclerView item child is visible.

**Comment by Vacxe** [comment]
I tried to reproduce this case with `sample` app and can't see any issue. 
If it possible could you modify for example `MultiTypeRecyclerTest` class to represent your issue?  It will definitely help us to recognise a tricky bug.
