### ISSUE TITLE
Bundled support libraries

### ISSUE THREAD

**Issue by tiwiz** [agoda-com/Kakao#31]
Would it be possible to bundle latest support library versions, instead of 25.4.0? It would be awesome to import those from the project, if they are good enough.

**Comment by Alviere** [comment]
I think we will put this in milestone for 1.1.0
For now, it should not be much trouble to exclude support libraries while importing it to your test dependencies.

**Comment by cdsap** [comment]
Hi @tiwiz, thank you very much for your feedback.
As @Alviere said we have included this issue for the milestone 1.1.0, more feedback is welcome  :)

**Comment by Alviere** [comment]
Issue is resolved, updated dependencies will be bundled in 1.1.0. Thanks for your contribution!
