### ISSUE TITLE
KAdapterItem with multiple layout types

### ISSUE THREAD

**Issue by Chesteer89** [agoda-com/Kakao#41]
Hi guys!

Is it possible to "ignore" some fields in KAdapterItem? I mean could it be nullable (and don't throw exception) when matching view is not found?

The problem is, i've got ListView with multiple view types, some contain TextView, some do not. I'd like to run some methods on them, like:

```
item?.apply {
  hasText("Sample text")
}
```

**Comment by Alviere** [comment]
Hi there!
For this kind of situation, you need to define your types of list items.
Just extend `KAdapterItem` (you can see how to do it in samples/readme.md) and specify views that this item contains. Then in your `KListView` provide all of your item types. After that simply use typed functions `childAt<YourItemType> { /* here you can access to views of specific item type */ }`. I'll provide an example below:
```
class TestListScreen : Screen<TestListScreen>() {
    val list = KListView(
            builder = { withId(R.id.list) },
            itemTypeBuilder = { 
                itemType(::Item)
                itemType(::Header)
            })

    class Item(i: DataInteraction) : KAdapterItem<Item>(i) {
        val title = KTextView(i) { withId(R.id.title) }
        val subtitle = KTextView(i) { withId(R.id.subtitle) }
        val button = KButton(i) { withId(R.id.button) }
    }
    
    class Header(i: DataInteraction) : KAdapterItem<Header>(i) {
        val header = KTextView(i) { withId(R.id.header_title) }
    }
}

fun test() {
    val screen = TestListScreen()

    screen { 
        list {
            childAt(0)<Header> { // casts first item in list to Header
                header { hasText("test") }
            }

            childAt(1)<Item> { // casts second item in list to Item
                title { hasText("testItem") }
            }
        }
    }
}
```

**Comment by Chesteer89** [comment]
Hi!

Thanks a lot! I already tried to pass more types but separated with comma :+1:

**Comment by Alviere** [comment]
You are welcome!
Anyway, I believe this problem is solved, so I'm closing this issue.
Thanks for using our library!
