### ISSUE TITLE
ListPopupWindow and Toast intergation

### ISSUE THREAD

**Issue by Chesteer89** [agoda-com/Kakao#42]
Hi guys!

First of all - thanks for your work!
Can you take a look on KToast and KListPopupWindow and give me some hints (maybe it's just an overkill and it could be done with KView and KListView?

https://gist.github.com/Chesteer89/767ad1b1584e2920a9758bd1dfe95b36
https://gist.github.com/Chesteer89/d6bfe7383c287935ce938e9dfa98c0a1

**Comment by Alviere** [comment]
Hey there! Thanks a lot for your interest in our project.
Regarding your question: it can be done via `KView` and `KListView`. We have `inRoot()` function located at `BaseAssertions`.
And we have `RootBuilder` class which helps you to perform this kind of checks.

Take a look at the example:
```kotlin
fun test() {
    screen { list { 
        inRoot { isPlatformPopup() } 
        childAt(0) { hasText("TEST") }
    } }
}

fun testToast() {
    screen { toast { 
        inRoot { withMatcher(ToastMatcher()) }
        hasText("TOAST")
    } }
}
```

**Comment by Chesteer89** [comment]
Are you sure we're able to get list in popup? 
What kind of matcher should i pass in Screen? (id is not set, withClassName doesnt work, withAnyText matches multiple views)

**Comment by Alviere** [comment]
You can try using `isInstanceOf` matcher for your list. And are you sure that list doesn't have an id?

**Comment by Alviere** [comment]
Also you can match the list by matching it's items with use of `withDescendant`

**Comment by Chesteer89** [comment]
Well, yes. We're using ListPopupWindow which doesnt have an id on list (contains DropDownListView). So the idea is to find a popup first (the real diff is **inAdapterView(matcher)** changed to **inRoot(RootMatchers.isPlatformPopup())**). 

Toast is similiar story. That's why I've changed view to:
`override val view = this.builder.getViewInteraction().inRoot(ToastMatcher())`

**Comment by Alviere** [comment]
For toast, as I said previously, you can declare a view with text matcher, for example, and then immediately apply root matcher:
```kotiln
val toast = KView {
    withText("TOAST")
} perform {
    inRoot { withMatcher(ToastMatcher()) }
}
```
This will return you the KView with view interaction inside, which already has root matcher.

Regarding ListView situation, I think we should ask someone else. @cdsap @VerachadW what do you guys think on this?

**Comment by VerachadW** [comment]
@Chesteer89 You may try to send the matcher for `list` with the parent matcher. The popup needs to anchor with the view or the screen window. So, I think we can create a matcher for the parent view and pass it to `withParent()` for `list`. This is my idea.

**Comment by Alviere** [comment]
We already have `withParent` matcher inside `ViewBuilder` class.

**Comment by Chesteer89** [comment]
Thanks guys! Optional parameter or `withParent()` sounds good.

I'll migrate to new version after update :)

Did you think about Snackbar tests? Is it possible right now or should i write my custom view + actions?

**Comment by Alviere** [comment]
No, right now we don't have prebuilt view classes for that, but this is good idea, to make `KSnackBar` and `KToast`. Is this issue resolved?

**Comment by ashdavies** [comment]
I'm currently trying to achieve the same thing here with an `AutoCompleteTextView` suggestion matcher (`PopupWindow`/`DropDownListView`), did you manage to find a resolve using `withParent()`?

**Comment by Unlimity** [comment]
Hi there!
The thing is, right now this behavior is not achievable due to specifics of these classes. `PopupWindow` and `Toast` actually create new `Window` instance when they show up. And espresso is explicitly bound to your activity's window with `ViewRootImpl` inside. It cannot access other windows through instrumentation.

**Comment by Unlimity** [comment]
We added `KSnackBar` support though.

**Comment by ashdavies** [comment]
My understanding is that you could use:
```
onData(equalTo("ITEM"))
  .inRoot(RootMatchers.isPlatformPopup())
  .perform(click())
```
for an autocomplete item?

I'm just not quite sure how to integrate that with a `KListView`, or if at all it's possible to do so at the moment.

**Comment by Unlimity** [comment]
As I recall, we have root matching.
So you can match your `KListView` by any means comfortable to you (by id, by class name, by searching through parent class name, etc.) and then apply root matcher during your actions/assertions:
```
screen {
  list {
    inRoot { isPlatformPopup() }
    // Do your stuff here
  }
}
```

**Comment by ashdavies** [comment]
Yep, but the difficulty is creating `list` in our `Screen<T>` class, the suggestion was to use `withParent` and `isRoot`, but I've not had much success, what might be a way of selecting it?

**Comment by Unlimity** [comment]
```
  val list = KListView(...) {
    isInstanceOf(ListView::class.java)
  }

  ...

  screen {
    list {
      inRoot { isPlatformPopup() }
      // Do your stuff here
    }
  }
```

**Comment by ashdavies** [comment]
That's what I've tried, but I'm getting a `NoMatchingViewException` 😞

**Comment by Unlimity** [comment]
Can you provide the dumps of layouts when you open your popup and the results of `adb shell dumpsys window windows` and `adb shell dumpsys activity`?

**Comment by Unlimity** [comment]
Also, what exact class do you use to spawn your popups?

**Comment by Unlimity** [comment]
I looked through the source code, and your view uses `ListPopupWindow` class inside, which uses `DropdownListView` class (not appcompat). So I would try to match by exact class name, not by parent class name.

**Comment by ashdavies** [comment]
Tried by class name also, the issue seems to be that the view hierarchy dumped with `NoMatchingViewException` is that of the activity window, which doesn't display the `DropDownListView` or the popup decor view, I've tried tweaking with `withParent`, `inRoot` to no avail 😞

**Comment by Unlimity** [comment]
Can you provide your screen class and test code where you try to access your list?

**Comment by ashdavies** [comment]
Sorry for the delay, I didn't see the notification
*Screen*
```
val list = KListView(
    builder = {
      isInstanceOf<ListView>()
      withParent {
        isRoot()
      }
    },
    itemTypeBuilder = {
      itemType(::Item)
    }
)

class Item(interaction: DataInteraction) : KAdapterItem<Item>(interaction) {

  val text = KTextView(interaction) {
    withId(android.R.id.text1)
  }
}
```

*Test*
screen {
  list {
    inRoot {
      isPlatformPopup()
    }
    firstChild<FinanceCalculatorScreen.Item> { 
      perform { 
        click()
      }
    }
  }
}

**Comment by Unlimity** [comment]
Hey there!
Try removing this:
```
withParent {
  isRoot()
}
```
I'm not sure that your list view is a direct descendant of platform popup view.

**Comment by ashdavies** [comment]
Still get a `NoMatchingViewException`, would it help if I submitted a PR to the samples with the problem I'm trying to solve?

**Comment by Unlimity** [comment]
I just noticed. `isInstanceOf<ListView>()` is very weird. Kakao doesn't have that function. Kakao's function signature is `isInstanceOf(clazz: Class<*>)`. It's not templated.

**Comment by ashdavies** [comment]
@Unlimity yep sorry this was an extension function in our code base, just an inline reified alias to Kakao's method

`inline fun <reified T> ViewBuilder.isInstanceOf(): Unit = isInstanceOf(T::class.java)`

**Comment by Unlimity** [comment]
Hm, I don't actually know how to help you now :(
Could you make a public repo with simple activity and test that reproduces your problem?

**Comment by ashdavies** [comment]
@Unlimity Hey! I've created a sample so you can see what I'm trying to achieve

**Comment by Unlimity** [comment]
Sure, I'll take a look as soon as I have free time
