### ISSUE TITLE
Add support for components from support design library

### ISSUE THREAD

**Issue by ghostbuster91** [agoda-com/Kakao#47]
It would be good to have support for components from android-support-design library.
Below is a list of actions/assertions which I found missing:
- TextInputEditText
  - has hint
  - has error
- NavigationDrawer
  - open/close
- SwipeRefreshLayout
  - swipeToRefresh
  - isLoading

Also it would be good to know how to interact with snackbar.

**Comment by Alviere** [comment]
Hi there and thanks for taking part in evolving our library!

NavigationDrawer is already supported. We have `KDrawerView` for that. It has `open` and `close` functions.
For SwipeRefreshLayout right now we don't have specific class, but for now you can use `KSwipeView` and call `swipeDown` function on it.
TextInputEditText and Snackbar right now are not in the library, but we are working to bring it out. Until then, you can make your own custom `KView` or make a PR here to support us.

I hope my answer was clear to you. Happy testing!

**Comment by Alviere** [comment]
Hello again! We're almost ready to release version `1.1.0`
In this version, you will have access to `KInputTextLayout`, `KNavigationView` and `KSwipeRefreshLayout` as well as `KSnackbar` which should cover your needs.
Thus, I'm closing this issue and hope that you will find this update very useful. Happy testing!
