### ISSUE TITLE
Cannot click on item in RecyclerView

### ISSUE THREAD

**Issue by 0v3rt1r3d** [agoda-com/Kakao#56]
Hi! I've some problems with the KRecyclerView. Every item in a recycler contains a linear layout with two or three TextViews. All I need is to click on item which contains a particular text. How can I do that?
  ```
  myKRecyclerView.childAt<MyKRecyclerItem>(withText(particularText));
  myKRecyclerView.childAt<MyKRecyclerItem>(withMatcher(ViewMatchers.withChild(ViewMatchers.withText(particularText))));
  ```
Both variants throw ``NoMatchingViewException``, but I see in the stack trace that the view with the text is contained in the recycler.

**Comment by Alviere** [comment]
Hey there! Thanks for your interest in Kakao
First of all, if you want to match some specific item, you have to use `childWith` function.
Second, `childWith` matches the root view of your RV item, and if you need to match item by it's child view, you need to specify it like that:
```kotlin
recyclerView { childWith<Item> { withDescendant { withText("test") } } perform { click() } }
```
You can also use our extension function `emptyChildWith` if you don't want to cast this item to any specific class, and just want to have basic actions and assertions:
```kotlin
recyclerView { emptyChildWith { withDescendant { withText("test") } } perform { click() } }
```
I hope my response fully covers the case. Happy testing!

**Comment by 0v3rt1r3d** [comment]
Yeah! I used ``childWith``, but copied another piece of code. Your answer helped me, thank you!

**Comment by Alviere** [comment]
Great, then I'm closing this issue.
