### ISSUE TITLE
Add seekbar support

### ISSUE THREAD

**Issue by ripzery** [agoda-com/Kakao#62]

**Comment by Alviere** [comment]
Hello there! Thank you for the submission, we will definetely add support for this widget in a minor release. Please stay tuned until then.

**Comment by ripzery** [comment]
Thank you!

**Comment by Alviere** [comment]
Actually, looking through Android SDK sources, `SeekBar` is a descendant of `ProgressBar`. So, there's need for adding a dedicated class. `KProgressBar` will do the job. Still, we might consider adding simulation of manual thumb dragging

**Comment by Alviere** [comment]
Support added. Hope it will work for you. Have a nice testing time!
