### ISSUE TITLE
Typo in Assertions

### ISSUE THREAD

**Issue by jschamburger** [agoda-com/Kakao#65]
Hi,

we just started using Kakao and it significantly improves the readability of our UI tests - thanks for that!
We noticed a small typo in method https://github.com/agoda-com/Kakao/blob/master/kakao/src/main/kotlin/com/agoda/kakao/Assertions.kt#L209. The function is called `doesNotExists` while the respective Espresso method is calls `doesNotExist`.
The two methods should have the same name to avoid confusion.

Thanks!

**Comment by cdsap** [comment]
Hi, 
thanks, we are planning to release a new version this week, we'll include the typo.

**Comment by jschamburger** [comment]
That's great, thanks for the quick response!

**Comment by Alviere** [comment]
Fixed. Thanks for pointing out!
