### ISSUE TITLE
Support AlertDialog

### ISSUE THREAD

**Issue by uziassantosferreira** [agoda-com/Kakao#71]
Is it possible add support to dialog?

**Comment by Alviere** [comment]
Hello there!
You can always access your dialog using `KView` and `isDialog` root matcher.
We might consider adding support for standard `AlertDialog` though in the upcoming releases.
Thanks for pointing out!

**Comment by uziassantosferreira** [comment]
Thanks 👍

**Comment by petrsvobodnikspider** [comment]
Hello, can provide an example how to use Root matcher with KView? There is no way how to provide view interaction when creating view

**Comment by Unlimity** [comment]
Hi there. There's a lot of examples of that in a different topics.
Anyway, here it is:
```
screen {
  list {
    inRoot { isPlatformPopup() }
    // Do your stuff here
  }
}
```

**Comment by petrsvobodnikspider** [comment]
Ohh I see, thank you so much

**Comment by Vacxe** [comment]
@uziassantosferreira @petrsvobodnikspider wanna let u know that this feature will be implemented by me ASAP

**Comment by Vacxe** [comment]
@olegosipenko FYI
