### ISSUE TITLE
Add ViewMatcher withContentDescription with resource identifier instead of String

### ISSUE THREAD

**Issue by JolandaVerhoef** [agoda-com/Kakao#72]
Currently it's only possible to match using a String content description. I think 

#### Steps to reproduce:

  1. Try to match a view based on it's content description id
  
#### Observed Results:

  * Compile error: Pass String instead of int
  
#### Expected Results:

  * Would like to be able to match on id, so that localisation doesn't give problems
  
#### Relevant Code:

  ```
val navigationIcon = KView {
        withContentDescription { R.string.cd_hamburger_icon }
    }
  ```

**Comment by VerachadW** [comment]
Hi, @JolandaVerhoef Thanks for submitting the issue. We will look into this or If you can submit the PR for it. We would really appreciate it. ^^
