### ISSUE TITLE
Question about the minSdkVersion

### ISSUE THREAD

**Issue by lowwor** [agoda-com/Kakao#83]
Any particular reason for using the minSdkVersion =16, because our project is using a minSdkVersion 14 and have some history problem to remain it there. It would be lovely that we can decrease it to 14, thank you.

**Comment by Alviere** [comment]
Hi there!
There's no particular reason to have it.
But I personally want to encourage the developers and community not to stick with legacy versions of Android.
If you really need to decrease `minSdkVersion`, contributions are welcome!

**Comment by lowwor** [comment]
I agreed, but our product manager don't think so. ╮(╯▽╰)╭. Pr submitted to use this great repo, see #86.
